services:
  naps-postgres:
    image: postgres:16
    container_name: naps-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - naps.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - naps-postgres:/var/lib/postgresql/data

  naps-downloader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: naps-downloader
    command: downloader
    env_file:
      - naps.env
    volumes:
      - naps-files:/raw

  naps-loader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: naps-loader
    command: loader
    depends_on:
      naps-postgres:
        condition: service_healthy
      naps-downloader:
        condition: service_completed_successfully
    env_file:
      - naps.env
    volumes:
      - naps-files:/raw

volumes:
  naps-postgres:
    name: naps-postgres
  naps-files:
    name: naps-files